### ISSUE TITLE
Support for captcha

### ISSUE THREAD

**Issue by mbertaboni** [jgriss/FusionSolarHA#1]
Hello, 
the component is not usable, because during the setup, in the login phase, there is a new captcha in verification phase.

"Login failed: Incorrect verification code."

Any chance to refactor the code maybe using username, password and the official API ( https://eu5.fusionsolar.huawei.com/thirdData/ )  ?

Thanks in advance for your work.

**Comment by jgriss** [comment]
Hi @mbertaboni 

Thanks a lot for the feedback!

The captcha response normally only appears after too many incorrect login attempts. This is reset after some time. In my setup, the library works for several months with about any captcha request sending around one query / minute.

I have to admit I wasn't aware of an official API. When I originally searched for one I couldn't find it. Also the link you posted returns a 404 for me. Can you point me to some official documentation about it?

Thanks a lot!

**Comment by mbertaboni** [comment]
Yep, you could start from here..

https://forum.huawei.com/enterprise/en/communicate-with-fusionsolar-through-an-openapi-account/thread/591478-100027

**Comment by jgriss** [comment]
Hi @mbertaboni,

The documentation shows that one needs to apply for an OpenAPI account for each plant separately. Additionally, usage of the API requires one to disable any SSL certificate verification. 
This will complicate the usage of the addon / python API quite a bit.
Therefore, I'll not change the tool yet.
If Huawei in the future changes this policy to also allow access to the "normal" user credentials, I'll revisit this issue again.

In the meantime, I hope that your captcha issue no longer occurred!

Kind regards,
Johannes
